app/src/main/java/Window/Grid.java
app/src/main/java/Window/README.md
app/src/main/java/Window/Window.java

window package test

---

.gitignore

Rimossa cartella bin di VScode

---

app/src/main/java/Window/Mouse.java
app/src/main/java/Window/Window.java

and the draw of a certain particle on the mouse
position

implemented mouse pressed and dragged listeners

---

app/src/main/java/Window/Mouse.java
app/src/main/java/Window/Window.java

the mouse cursor circle changes size with scroll wheel

changed mouse scroll wheel to adjust radius size

---

app/src/main/java/Blocks/Liquids/LiquidParticle.java
app/src/main/java/Blocks/Liquids/Water.java
app/src/main/java/Blocks/Solids/DynamicSolid/Gravel.java
app/src/main/java/Blocks/Solids/DynamicSolid/Snow.java
app/src/main/java/Blocks/Solids/SolidParticle.java
app/src/main/java/Blocks/Solids/StaticSolid/StaticParticle.java
app/src/main/java/Window/Window.java

adesso matteo fixa l'acqua che devo andare a giocare a beach volley

Added LiquidParticle, Gravel and Water

---

app/src/main/java/Blocks/Liquids/LiquidParticle.java
app/src/main/java/Blocks/Solids/DynamicSolid/DynamicParticle.java

Fixed falling of Water, Changed Gravel behavior. Made so Freefalling doesnt happen in liquids

---

app/src/main/java/Window/Mouse.java
app/src/main/java/Window/Window.java

The cricle is now pixelated, I startes doing the part for it to place the circle of pixel, didn't have time so i commented those parts pls don't delete them

FixedMouseCricle

---

app/src/main/java/Window/Mouse.java
app/src/main/java/Window/Window.java

The Mouse now has a max size

---

app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/Player.java
app/src/main/java/Window/Window.java

Movable player (WASD) and entity class extending jpanel

Movable player and entity class

---

app/src/main/java/Blocks/ParticleList.java
app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/EntityParticle.java
app/src/main/java/Entities/Player.java
app/src/main/java/Window/Window.java

Implemented a new particle for the entities

---

app/src/main/java/Blocks/Liquids/LiquidParticle.java
app/src/main/java/Blocks/Solids/DynamicSolid/DynamicParticle.java
app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/EntityParticle.java
app/src/main/java/Entities/Player.java
app/src/main/java/Window/Window.java

player affected by gravity, no longer messes creating purple particles

player affected by gravity, no longer messes creating purple particles

---

app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/EntityParticle.java
app/src/main/java/Entities/Player.java

Player is completely bounded inside the grid. Jump must be implemented

Player is completely bounded inside the grid. Jump must be implemented

---

app/src/main/java/Blocks/ParticleList.java
app/src/main/java/Blocks/Solids/DynamicSolid/DynamicParticle.java
app/src/main/java/Entities/Entity.java
app/src/main/java/Grid/Grid.java
app/src/main/java/Window/Window.java

player jump not done

---

app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/Player.java
app/src/main/java/Grid/Grid.java

Player bug fixes

---

app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/Player.java

New Entity logic almost finished

New Entity logic almost finished

---

app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/EntityParticle.java
app/src/main/java/Launcher/Launcher.java

Entity logic almost done

---

app/src/main/java/Entities/Entity.java

Enitity logic SHOULD work

---

app/src/main/java/Blocks/Solids/StaticSolid/StaticParticle.java
app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/Player.java
app/src/main/java/Window/Window.java

Entity finally works

---

app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/Player.java
app/src/main/java/Grid/Grid.java
app/src/main/java/Window/Window.java

view following player

---

app/src/main/java/Entities/Entity.java
app/src/main/java/Entities/Player.java
app/src/main/java/Window/Window.java

minor fixes
